import {cars} from "../../img/Guest/cars/cars";


export const carsInfo = [
    {
        img: cars.audi,
        fullName: "Audi A1 S-Line",
        model: "Audi",
        mark: "A1",
        price: 45,
        year: "2012",
        doors: "4/5",
        ac:"Yes",
        transmission: "Manual",
        fuel: "Gasoline"},
    {
        img: cars.vwGolf,
        fullName: "VW Golf 6",
        model: "Golf 6",
        mark: "Volkswagen",
        price: 37,
        year: "2008",
        doors: "4/5",
        ac: "Yes",
        transmission: "Manual",
        fuel: "Diesel"},
    {
        img: cars.camry,
        fullName: "Toyota Camry",
        model: "Camry",
        mark: "Toyota",
        price: 30,
        year: "2006",
        doors: "4/5",
        ac: "Yes",
        transmission: "Automatic",
        fuel: "Hybrid"},
    {
        img: cars.bmw,
        fullName: "BMW 320 ModernLine",
        model: "320",
        mark: "BMW",
        price: 35,
        year: "2012",
        doors: "4/5",
        ac: "Yes",
        transmission: "Manual",
        fuel: "Diesel"},
    {
        img: cars.mercedes,
        fullName: "Mercedes-Benz GLK",
        model: "Benz GLK",
        mark: "Mercedes",
        price: 50,
        year: "2006",
        doors: "4/5",
        ac: "Yes",
        transmission: "Manual",
        fuel: "Diesel"},
    {
        img: cars.vwPass,
        fullName: "VW Passat CC",
        model: "Passat CC",
        mark: "Volkswagen",
        price: 25,
        year: "2008",
        doors: "4/5",
        ac: "Yes",
        transmission: "Automatic",
        fuel: "Gasoline"},
]